site_name: AiHub 使用手册
site_url: https://lixajh.github.io/aihub-docs
theme:
  name: material
  language: zh
  features:
    - content.images.zoom
markdown_extensions:
  - attr_list
use_directory_urls: false
plugins:
  - glightbox
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 产品简介: index.md  
  - 快速入门:
      - 登录注册: 登录注册.md
      - 标注人员操作指南: 标注人员操作指南.md
      - 算法人员操作指南: 算法人员操作指南.md
      - 快速开始-创建模型训练任务: 快速开始-创建模型训练任务.md
      - 快速开始-创建工作流任务: 快速开始-创建工作流任务.md
  - 操作指南:
      - Dashboard: Dashboard.md
      - 任务中心: 
          - 任务管理: 任务管理.md
          - 工时管理: 工时管理.md
          - 数据标注任务: 数据标注任务.md
          - 数据接入任务: 数据接入任务.md
          - 外网数据下载任务: 外网数据下载任务.md
      - 文档中心: 文档中心.md
      - 数据仓库: 数据仓库.md
      - 数据集管理: 数据集管理.md
      - 数据标注:
          - 标注项目管理: 标注项目管理.md
          - 数据集格式: 
              - COCO: 数据集格式_COCO.md
              - VOC: 数据集格式_VOC.md
              - IF_DATA: 数据集格式_IF_DATA.md
              - 视频标注: 数据集格式_视频标注.md
              - 档案清洗合并: 数据集格式_档案清洗合并.md
          - 数据标注: 
              - 目标检测: 目标检测.md
              - 图像分类: 图像分类.md
              - 视频分类: 视频分类.md
              - 视频标注: 视频标注.md
              - 档案清洗合并: 档案清洗合并.md
              - 快捷键说明: 快捷键说明.md
          - 数据导出: 数据导出.md
          - 标注质量管理: 
              - 数据集可视化: 数据集可视化.md
              - 一致性测试: 一致性测试.md
              - 数据质检: 数据质检.md
              - 问题中心: 问题中心.md
          - 标注团队管理: 标注团队管理.md
          - 绩效管理: 绩效管理.md
      - 镜像管理: 镜像管理.md
      - 工作流管理: 工作流管理.md
      - 模型训练: 模型训练.md
      - 模型部署: 模型部署.md